version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./db/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  #rust-websocket:
  #  build: ./socket-server
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./socket-server:/usr/src/app
  #  environment:
  #    - RUST_BACKTRACE=1

  go-filesystem:
    build: ./hive-fileservice
    ports:
      - "8081:8081"
    volumes:
      - ./hive-fileservice:/app
    environment:
      - GO_ENV=development
