/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tPFVqYRpyIr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function MainContent() {
  const [view, setView] = useState("view")
  return (
    <div className="flex min-h-screen w-full flex-col bg-muted/40">
      <header className="sticky top-0 z-30 flex h-14 items-center justify-between border-b bg-background px-4 sm:px-6">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">Acme Inc</span>
        </Link>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" className="flex items-center gap-2">
              <FolderIcon className="h-5 w-5" />
              <span>Projects</span>
              <ChevronDownIcon className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="start" className="w-[300px]">
            <DropdownMenuLabel>Your Projects</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>
              <FileIcon className="h-4 w-4 mr-2" />
              <div className="flex-1">
                <div className="font-medium">Dashboard</div>
                <div className="text-muted-foreground">acme.com</div>
              </div>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <FolderIcon className="h-4 w-4 mr-2" />
              <div className="flex-1">
                <div className="font-medium">Marketing Site</div>
                <div className="text-muted-foreground">marketing.acme.com</div>
              </div>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <FileIcon className="h-4 w-4 mr-2" />
              <div className="flex-1">
                <div className="font-medium">Blog</div>
                <div className="text-muted-foreground">blog.acme.com</div>
              </div>
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>
              <PlusIcon className="h-4 w-4 mr-2" />
              Create New Project
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        <Button variant="ghost" size="icon" className="rounded-full">
          <LogOutIcon className="h-5 w-5" />
          <span className="sr-only">Logout</span>
        </Button>
      </header>
      <div className="flex flex-1 overflow-hidden">
        <nav className="flex flex-col gap-2 border-r bg-background p-4">
          <Button variant="ghost" className="flex items-center justify-start gap-2">
            <FolderIcon className="h-5 w-5" />
            <span>src</span>
          </Button>
          <Collapsible className="grid gap-2">
            <CollapsibleTrigger className="flex items-center justify-start gap-2">
              <FolderIcon className="h-5 w-5" />
              <span>components</span>
              <ChevronRightIcon className="ml-auto h-5 w-5 transition-all" />
            </CollapsibleTrigger>
            <CollapsibleContent>
              <div className="grid gap-2 pl-4">
                <Button variant="ghost" className="flex items-center justify-start gap-2">
                  <FileIcon className="h-5 w-5" />
                  <span>Header.js</span>
                </Button>
                <Button variant="ghost" className="flex items-center justify-start gap-2">
                  <FileIcon className="h-5 w-5" />
                  <span>Sidebar.js</span>
                </Button>
                <Button variant="ghost" className="flex items-center justify-start gap-2">
                  <FileIcon className="h-5 w-5" />
                  <span>Main.js</span>
                </Button>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid gap-2">
            <CollapsibleTrigger className="flex items-center justify-start gap-2">
              <FolderIcon className="h-5 w-5" />
              <span>pages</span>
              <ChevronRightIcon className="ml-auto h-5 w-5 transition-all" />
            </CollapsibleTrigger>
            <CollapsibleContent>
              <div className="grid gap-2 pl-4">
                <Button variant="ghost" className="flex items-center justify-start gap-2">
                  <FileIcon className="h-5 w-5" />
                  <span>Home.js</span>
                </Button>
                <Button variant="ghost" className="flex items-center justify-start gap-2">
                  <FileIcon className="h-5 w-5" />
                  <span>About.js</span>
                </Button>
                <Button variant="ghost" className="flex items-center justify-start gap-2">
                  <FileIcon className="h-5 w-5" />
                  <span>Contact.js</span>
                </Button>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Button variant="ghost" className="flex items-center justify-start gap-2">
            <FileIcon className="h-5 w-5" />
            <span>App.js</span>
          </Button>
        </nav>
        <main className="flex-1 p-4 sm:p-6">
          <Card className="h-full">
            <CardHeader className="flex items-center justify-between border-b pb-4">
              <div className="grid gap-2">
                <h2 className="text-2xl font-bold">Dashboard</h2>
                <p className="text-muted-foreground">This is the main dashboard for your application.</p>
              </div>
              <div className="flex items-center gap-4">
                <Button variant={view === "view" ? "primary" : "outline"} onClick={() => setView("view")}>
                  View
                </Button>
                <Button variant={view === "edit" ? "primary" : "outline"} onClick={() => setView("edit")}>
                  Edit
                </Button>
              </div>
            </CardHeader>
            <CardContent className="flex-1 p-4 sm:p-6">
              {view === "view" && (
                <div className="grid gap-4">
                  <div className="grid gap-2">
                    <h3 className="text-xl font-bold">Key Metrics</h3>
                    <div className="grid grid-cols-2 gap-4">
                      <Card>
                        <CardContent className="flex items-center justify-between">
                          <div>
                            <h4 className="text-4xl font-bold">1,234</h4>
                            <p className="text-muted-foreground">Users</p>
                          </div>
                          <UserIcon className="h-8 w-8" />
                        </CardContent>
                      </Card>
                      <Card>
                        <CardContent className="flex items-center justify-between">
                          <div>
                            <h4 className="text-4xl font-bold">$12,345</h4>
                            <p className="text-muted-foreground">Revenue</p>
                          </div>
                          <DollarSignIcon className="h-8 w-8" />
                        </CardContent>
                      </Card>
                      <Card>
                        <CardContent className="flex items-center justify-between">
                          <div>
                            <h4 className="text-4xl font-bold">98%</h4>
                            <p className="text-muted-foreground">Retention</p>
                          </div>
                          <PercentIcon className="h-8 w-8" />
                        </CardContent>
                      </Card>
                      <Card>
                        <CardContent className="flex items-center justify-between">
                          <div>
                            <h4 className="text-4xl font-bold">4.9</h4>
                            <p className="text-muted-foreground">Rating</p>
                          </div>
                          <StarIcon className="h-8 w-8" />
                        </CardContent>
                      </Card>
                    </div>
                  </div>
                </div>
              )}
              {view === "edit" && (
                <div className="grid gap-4">
                  <div className="grid gap-2">
                    <h3 className="text-xl font-bold">Edit Dashboard</h3>
                    <p className="text-muted-foreground">Customize the dashboard to your liking.</p>
                  </div>
                  <div className="grid gap-4">
                    <div className="grid gap-2">
                      <Label htmlFor="title">Title</Label>
                      <Input id="title" defaultValue="Dashboard" />
                    </div>
                    <div className="grid gap-2">
                      <Label htmlFor="description">Description</Label>
                      <Textarea id="description" defaultValue="This is the main dashboard for your application." />
                    </div>
                    <div className="grid gap-2">
                      <Label htmlFor="metrics">Key Metrics</Label>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="grid gap-2">
                          <Label htmlFor="users">Users</Label>
                          <Input id="users" defaultValue="1,234" />
                        </div>
                        <div className="grid gap-2">
                          <Label htmlFor="revenue">Revenue</Label>
                          <Input id="revenue" defaultValue="$12,345" />
                        </div>
                        <div className="grid gap-2">
                          <Label htmlFor="retention">Retention</Label>
                          <Input id="retention" defaultValue="98%" />
                        </div>
                        <div className="grid gap-2">
                          <Label htmlFor="rating">Rating</Label>
                          <Input id="rating" defaultValue="4.9" />
                        </div>
                      </div>
                    </div>
                    <div className="flex justify-end gap-2">
                      <Button variant="outline">Cancel</Button>
                      <Button>Save</Button>
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </main>
      </div>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}


function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}


function FolderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  )
}


function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PercentIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="19" x2="5" y1="5" y2="19" />
      <circle cx="6.5" cy="6.5" r="2.5" />
      <circle cx="17.5" cy="17.5" r="2.5" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
